sudo: required
dist: trusty
language: node_js
node_js: '11.6'
branches:
  only:
  - master
before_install:
  - git submodule init
  - git submodule update --remote
install:  
  - npm install
script:
  - npm test